yabauseut/src/dsp.c
SCUREG doesn't match the defines in scuregs.h
=> Change SCUREG to SCU_REG to fix compile errors.

yabauseut/src/vdp2.c
The two new tests are for extended color calculation and Vdp2 sprite effects like shadows, priority and color calculation.
=> Add two new tests and fix cycle pattern register bug

yabauseut/src/vdp2.c
Make the register variables adjustable and add some presets. Also add line screen support.
=> Make the extended color calculation test more comprehensive

yabauseut/src/vdp2.c
This test demonstrates the two line windows by using two ellipses to mask parts of the background layers.
=> Add a test for the Vdp2 line window.

yabause/src/vidsoft.c
=> Fix Albert Odyssey title screen regression.

yabause/src/CMakeLists.txt, yabause/src/persdljoy.c, yabause/src/sndsdl.c, yabause/src/yabause.c
Added libSDL2 definition to CmakeList and fixed include for OS X
=> OS X fixes

.travis.yml, appveyor.yml, yabause/src/CMakeLists.txt, yabause/src/qt/ui/UIYabause.cpp
Fixed issues https://github.com/Yabause/yabause/issues/138 and https://github.com/Yabause/yabause/issues/139
=> Fixed a couple of issues with appveyor/travis-ci, security fixes, etc.

yabause/src/vidsoft.c
This patch checks if vdp1 draw commands are outside of the valid area and skips them if possible. Nights increases from around 73 to 83 fps on my system.
This also prevents some extreme slowdowns that occur during the intro of Cotton Boomerang and when the first boss appears in Radiant Silvergun.
=> vidsoft: implement vdp1 pre-clipping optimization

yabause/src/vidsoft.c
#175 Night Warriors uses the last part of the vdp1 framebuffer as scratch ram, which was being overwritten due to the clipping settings not being latched properly. 32-bit framebuffer writes needed to be implemented as well.
This commit also fixes a vdp1 thread race condition when games try to read and write the framebuffer.
=> vidsoft: fix night warriors sprites

yabause/src/m68kc68k.c, yabause/src/m68kcore.c, yabause/src/m68kcore.h, yabause/src/m68kq68.c, yabause/src/scsp.c
All of the 68k state needs to be saved to make it deterministic. IMPROVED_SAVESTATES needs to be defined to enable this.
=> improve 68000 savestates

yabause/src/vidsoft.c
This game enables and disables backgrounds mid screen. Fixes #189
=> vidsoft: fix f1 challenge map when zoomed out

yabause/src/vidsoft.c, yabauseut/src/vdp2.c
Fixes interlace mode bugs, off-by-one bugs in a few games, and runs a little faster.
=> vidsoft: improve user and system clipping

yabause/src/vidsoft.c
=> vidsoft: fix sprite window in cotton boomerang and winter heat

yabause/src/vdp2.c, yabause/src/vdp2.h, yabause/src/vidshared.h, yabause/src/vidsoft.c
This game updates the vertical cell scroll table and map registers mid frame.
=> vidsoft: improve sonic 2 two player mode

yabause/src/peripheral.c, yabause/src/qt/ui/UIYabause.cpp, yabause/src/qt/ui/UIYabause.h
=> Fixed issues with emulated mouse and qt mouse

yabause/src/scsp.c
An example of the difference can be heard in this video: https://raw.githubusercontent.com/d356/yabause-ci-test/master/scsp-fm.mp4 The fm sounds in the bios are played on the current scsp followed by this one.
The new scsp is enabled with the USE_NEW_SCSP define because it is still missing some features.
=> scsp: implement new slot generation method with fm support

yabause/src/scsp.c, yabause/src/scspdsp.c, yabause/src/scspdsp.h, yabause/src/yabause.c
This commit implements enough of the scsp dsp to enable reverb and echo effects in the bios intro and Radiant Silvergun.
=> new scsp: implement dsp

yabause/src/vidsoft.c, yabauseut/src/scsp.c
This should fix the crashing issue in #199. Some scsp tests have also been added.
=> vidsoft: improve sprite window bounds checking

yabause/src/qt/CMakeLists.txt, yabause/src/qt/ui/UIDebugSCSPChan.cpp, yabause/src/qt/ui/UIDebugSCSPChan.h, yabause/src/qt/ui/UIYabause.cpp, yabause/src/qt/ui/UIYabause.h, yabause/src/qt/ui/UIYabause.ui, yabause/src/scsp.c, yabause/src/scsp.h
Channel volumes should be more correct now. This also adds a debug dialog that allows for viewing envelope states and muting instruments.
=> new scsp/qt :improve send levels and add channel debug dialog

yabause/src/CMakeLists.txt, yabause/src/aosdk/ao.h, yabause/src/aosdk/corlett.c, yabause/src/aosdk/corlett.h, yabause/src/aosdk/eng_ssf.c, yabause/src/aosdk/license.txt, yabause/src/aosdk/ssf.c, yabause/src/aosdk/ssf.h, yabause/src/qt/YabauseThread.cpp, yabause/src/qt/ui/UIYabause.cpp, yabause/src/qt/ui/UIYabause.h, yabause/src/qt/ui/UIYabause.ui, yabause/src/scsp.c, yabause/src/yabause.c, yabause/src/yabause.h
LFO improves Nights and Shinobi X. The ssf player is based on https://github.com/cyberwarriorx/yabber and aosdk.
=> new scsp / qt: add plfo, alfo, ssf playing

yabause/src/runner/yui.cpp, yabause/src/scsp.c
This should resolve the issue reported in https://github.com/Yabause/yabause/pull/214
=> new scsp: fix crash on 32 bit systems

.travis.yml
Currently musashi and the dynarec are not built.
=> ci: add android port to travis

mini18n/src/CMakeLists.txt, mini18n/src/mini18n_pv_file_csv.c, mini18n/src/mini18n_pv_file_csv.h, mini18n/src/mini18n_pv_hash.c, yabause/l10n/yabause_ar.yts, yabause/l10n/yabause_de.yts, yabause/l10n/yabause_es.yts, yabause/l10n/yabause_fr.yts, yabause/l10n/yabause_it.yts, yabause/l10n/yabause_ja.yts, yabause/l10n/yabause_lt.yts, yabause/l10n/yabause_nl.yts, yabause/l10n/yabause_pt.yts, yabause/l10n/yabause_pt_BR.yts, yabause/l10n/yabause_ru.yts, yabause/l10n/yabause_sv.yts, yabause/l10n/yabause_zh_CN.yts, yabause/l10n/yabause_zh_TW.yts
Yabause is now being translated at https://www.transifex.com/yabause/public/
=> i18n: magneto csv parsing, convert yts files, add missing strings

yabause/src/scu.c
This is the fix for Grandia boot.
https://github.com/devmiyax/yabause/issues/29
(cherry picked from commit 28ee78dc23122e74785a8ce8ed8af9cb40dd31eb)
=> refs #29 Grandia red Screen.

yabause/src/scu.c
This is the implementation of 'DxFT2-0[x=2-0](Ｗ)　　DMA level 2-0 starting FacTor bit2-0' 
(cherry picked from commit 0c1af88f17fe0221cd7522bfc2b42c39de178e60)
=> 3.2 SCU DMA interrupt start factor

yabause/src/CMakeLists.txt, yabause/src/qt/QtYabause.cpp, yabause/src/sh2_jit.cpp, yabause/src/sh2_jit.h, yabause/src/sh2core.h, yabause/src/sh7034.c
=> sh1: add dynarec

yabause/src/android/AndroidManifest.xml, yabause/src/android/build.gradle, yabause/src/android/res/layout-v11/save_item.xml, yabause/src/android/res/layout/game_item.xml, yabause/src/android/res/layout/save_item.xml, yabause/src/android/src/org/yabause/android/PadManagerV16.java, yabause/src/android/src/org/yabause/android/SaveListAdapter.java, yabause/src/android/src/org/yabause/android/SaveListModeListener.java, yabause/src/android/src/org/yabause/android/Yabause.java, yabause/src/android/src/org/yabause/android/YabausePad.java, yabause/src/android/src/org/yabause/android/YabauseView.java
- ArrayList => ArrayList<Integer>
- Removed deprecated and useless SURFACE_TYPE_GPU
- Disabled backup
- Using valueOf instead of ctors
- Moved allocation out of draw code
- HashMap => SparseIntArray
- Avoid using default Locale
- Added missing 'public' qualifiers
- Added TargetApi annotation
- Removed useless namespace declarations
=> Fixed various problems in Android port

yabause/src/thr-linux.c
Now using pthread condition variables instead of pause/signal.
This makes it possible to use threads in the Android port.
=> Rewrote thread sleep/wake for Linux
