Yabause/yabause

- yabause/src/qt/ui/UIDebugSH2.cpp
- yabause/src/qt/ui/UIHexEditor.cpp
- yabause/src/qt/ui/UIHexEditor.h
- yabause/src/qt/ui/UIMemoryEditor.cpp
- yabause/src/qt/ui/UIMemoryEditor.h
- yabause/src/qt/ui/UIMemoryEditor.ui
Fixed bug with dumping selected memory where selection wasn't being dumped fully.  Also added Save Tab for dumping memory which will dump the current memory tab you're on.
> Memory Dump Fixes

- yabauseut/src/vdp1.c
The user clipping mode can be selected with the A, B and C buttons.  Here is an image of it running on real hardware, showing the outside drawing mode.
> Add a test demonstrating vdp1 system and user clipping.

- yabause/src/vidsoft.c
Outside clipping only displays sprite pixels outside the user clipping coordinates.
Before:
After:
> Add support in vidsoft.c for vdp1 outside clipping mode.

- yabauseut/src/vdp2.c
This test demonstrates the regular scroll screens in tile mode by uploading a font to vram and setting the pattern name data to show messages.  The screens are then scrolled in different directions when the user presses the A button. This test has not been made accessible from the menu but adding a call to vdp2_all_scroll_test() somewhere should load it correctly.
> Add a test demonstrating the Vdp2 scroll screens in tile mode.

- yabause/src/titan/titan.c
- yabause/src/vidsoft.c
- yabauseut/src/vdp2.c
Running the test and pressing up, left or right will set the test to the settings that are fixed by this patch. Additional settings can be tested with the other buttons. The settings look as follows on hardware:
Yabause should now produce the same results as the hardware for these settings.
> Add line color screen test and fixes

- yabause/src/vidsoft.c
- yabauseut/src/vdp2.c
Add a test for special priority and fix per-pixel priority in vidsoft. Press 'A' in the test to change presets. Preset 1 and 4 of the test should now match hardware. With preset 1 the blocks should blink in a checker pattern. In test 4, every other block should be invisible like seen below.
Preset 1
Preset 4
> Special priority test and emulation fixes

- yabause/src/vidsoft.c
- yabauseut/src/vdp2.c
The line scroll interval bit allows for line scroll to happen at 1,2,4 or 8 line intervals.  With this change horizontal line scroll and line zoom should now match hardware for all 4 interval settings.  In the test, set "Horiz ln scrl enab" or "Line zoom enable" to 1 and "Line scrll intrvl" from 0-3 to check the different settings.
> Add support for the line scroll interval bit in vidsoft.c

- .travis.yml
Travis CI is a continuous integration service that is free for open source projects and integrates with GitHub easily.  
This .travis.yml file sets up four build types: Linux/GCC Qt, Linux/Clang Qt, OS X Cocoa, and MinGW-w64 Windows cross compile. MinGW-w64 only compiles libyabause due to the amount of time it would take to compile Qt.
An example of the output can be viewed at the following link: https://travis-ci.org/d356/yabause/builds/74776583
Build Jobs 1-4 represent the 4 build types mentioned above respectively.
> Add continuous integration with Travis CI.

- appveyor.yml
Appveyor is a service like Travis CI but supports Windows.  This yml file sets up a Visual Studio 2013 x64 build and a Mingw32 x86 build. An example of the output can be seen here:
https://ci.appveyor.com/project/d356/yabause/build/1.0.107
This script also packages the output into a zip file so that it can be downloaded and tested. An example can be seen here:
https://ci.appveyor.com/project/d356/yabause/build/1.0.107/job/ukj3jt16kavxamhx/artifacts
> Add Windows continuous integration with Appveyor

- .travis.yml
- yabause/src/CMakeLists.txt
- yabause/src/android/jni/yui.c
- yabause/src/cocoa/YabauseController.m
- yabause/src/dreamcast/yui.c
- yabause/src/gtk/main.c
- yabause/src/qt/YabauseThread.cpp
- yabause/src/runner/CMakeLists.txt
- yabause/src/runner/yui.c
- yabause/src/yabause.c
- yabause/src/yabause.h
- yabauseut/CMakeLists.txt
- yabauseut/src/main.c
- yabauseut/src/tests.c
- yabauseut/src/tests.h
This commit adds a method for checking for the presence of emulation regressions automatically. The "runner" port, which is a headless port of Yabause that communicates with YabauseUT and prints test output to the command line, is compiled and run at the same time as the regular builds on Travis CI. YabauseUT has been modified to have a interface for sending text to Yabause. The build output of the 5th build on Travis CI will show any regressions that have occurred. An example can be seen here:
https://travis-ci.org/d356/yabause/jobs/75701381
Currently a YabauseUT binary is fetched from GitHub but in the future it could be compiled on the fly. Tests that are expected to fail should be added to runner/yui.c to prevent Travis CI from saying that the build caused an error.
> Add a system for automated emulation regression testing

- yabause/src/runner/yui.c
- yabause/src/scu.c
- yabauseut/src/dsp.c
- yabauseut/src/dsp.h
These fixes correct flag handling bugs in the SCU DSP and can be verified with the included test. The test compares the ALU results to a table generated by hardware. The 11 different ALU instructions can be cycled through by pressing start. Incorrect values are marked red. The final 4 results of the sign flag in the RR test are incorrect because of a different bug in computing the RR result.
For an example here is the ADD instruction on hardware:
> Fix SCU DSP flag handling bugs

- .travis.yml
- yabause/src/qt/QtYabause.h
- yabause/src/qt/ui/UIDebugSCSPDSP.cpp
- yabause/src/scsp.c
- yabause/src/scspdsp.c
- yabause/src/scspdsp.h
- yabause/src/yabause.c
- yabauseut/src/main.c
- yabauseut/src/scsp.c
- yabauseut/src/scsp.h
Writes and reads for coef, madrs and mpro now work. The disassembler doesn't attempt to regenerate the original program, but just print out which bits are set in each instruction. 
Also checkout a specific yabauseut binary to prevent build breakage.
> Implement some SCSP DSP register writes and a disassembler

- .travis.yml
- yabause/src/runner/CMakeLists.txt
- yabause/src/runner/yui.c
- yabause/src/runner/yui.cpp
- yabauseut/src/main.c
- yabauseut/src/scsp.c
- yabauseut/src/tests.c
- yabauseut/src/tests.h
- yabauseut/src/vdp2.c
- yabauseut/src/vdp2.h
The runner port now takes screenshots of Vdp2 tests with Vidsoft and compares them to known good images. If there is a mismatch it will print out the x,y coordinates of the first mismatched pixel and the color value.  
Some of these tests don't actually run correctly on Yabause, but I think Saturn video capture is too inaccurate to allow a comparison to shots from real hardware. However this system can still be used to find unintended regressions. 
The current screenshots that are being compared can be viewed here: https://github.com/d356/yabauseut-bin/commit/9875a6f113bc796b68bd484245e709a04548d7cc
> Add Vdp2 screenshot automated testing

- .travis.yml
- yabause/src/runner/yui.cpp
- yabauseut/src/main.c
- yabauseut/src/tests.c
- yabauseut/src/tests.h
- yabauseut/src/vdp1.c
- yabauseut/src/vdp1.h
The runner port can now compare Vdp1 framebuffer captures from actual hardware to Yabause's vidsoft Vdp1. 
[Coverity] (https://scan.coverity.com/) is a free service for open source projects that does analysis to look for bugs. The travis.yml file needs a few changes to work on this fork of Yabause. The project name needs to be changed to Yabause/yabause and the secure token needs to be changed to the repository owner's token, which can be generated on Coverity's website.
After signing up for Coverity, a scan can be started by pushing to the coverity_scan branch. I did not set up the master branch for scanning because there are a limited number of scans allowed per week, and there seems to be no way to prevent Coverity from scanning all 5 builds on Travis CI. When the coverity_scan branch …
> Add Vdp1 automated framebuffer testing and Coverity on Travis CI

- yabause/src/CMakeLists.txt
- yabause/src/runner/CMakeLists.txt
- yabauseut/CMakeLists.txt
- yabauseut/src/CMakeLists.txt
Some versions of Cmake seem to be more strict about having cmake_minimum_required() present.
The hard-coded paths in  yabauseut/CMakeLists.txt make it hard to compile on linux. These paths can be specified on the command line with the -D prefix.
By default Cmake wants a C++ compiler present. Adding "C" to project declarations makes it so that Cmake doesn't check for one and error if it isn't available.
> Build fixes for newer Cmake, linux, allow building without a C++ compiler

- circle.yml
CircleCI is a continuous integration service that allows the usage of Docker images and is free for open source projects. As far as I know, CircleCI is the only one that allows this. 
With Docker, a container can be created with a pre-compiled sh-elf-gcc on it suitable for compiling Saturn binaries.
The Dockerfile that creates the sh toolchain can be seen here: https://github.com/d356/sh2-gcc-docker/blob/master/sh2-gcc/Dockerfile
That Dockerfile results in a pre-built container that is stored on Dockerhub.
That base container is fetched from Dockerhub and used in another Dockerfile that compiles Iapetus, YabauseUT, yabause-runner, and then runs the tests.
The second Dockerfile can be seen here: https://github.com/d356/yabauseut-docker/blob/master/Dockerfile
CircleCI automatically clones …
> Build and test YabauseUT on CircleCI using Docker

- .travis.yml
- appveyor.yml
- yabause/src/vidsoft.c
- yabauseut/src/vdp2.c
Fixes Wonderboy in FBA Saturn.
I don't think per-pixel priority can be 100% fixed unless priority handling is moved so that it takes place after pixel generation.
Here is an example:
Nbg0 is drawn at priority 1. Then nbg1 is drawn at priority 0, and some pixels are raised to priority 1 using special priority. Since nbg1 is drawn after nbg0, the pixels raised to priority 1 will overwrite nbg0 pixels. However this is incorrect, since nbg0 has a higher priority than nbg1 when they have the same priority.
> Improve per-pixel special priority

- yabause/src/CMakeLists.txt
- yabause/src/titan/titan.c
- yabause/src/titan/titan.h
- yabause/src/vidshared.h
- yabause/src/vidsoft.c
This PR fixes the special priority case mentioned in my previous PR by moving blending and priority to after the pixels have been generated. This also makes it possible to multi-thread the rendering in two places. Both kinds of multi-threading can be enabled with -DYAB_WANT_VIDSOFT_RENDER_THREADING=ON and -DYAB_WANT_VIDSOFT_LAYER_THREADING=ON . RENDER_THREADING threads the blending and pixel sorting. LAYER_THREADING generates the layers in different threads. The multi-threading requires OpenMP, which is included with GCC, LLVM and Visual Studio. 
I haven't updated the images for the tests yet, so the CircleCI build will fail at the moment.
> Improve special priority and add optional multi-threading to vidsoft

- yabause/src/vidsoft.c
- yabauseut/src/vdp2.c
Burning Rangers, Cotton Boomerang, Nights, Scud and Winter Heat were tested and seem to work fine. High res support has been added to a few YabauseUT tests and Yabause matches the hardware for all those cases now. This patch does not change vertical resolution handling.
> Improve horizontal high resolution support

- yabause/src/vidsoft.c
Rbg0 is always the same size, even in hi-res mode.
> Fix Rbg0 in Dead or Alive

- yabause/src/titan/titan.c
- yabause/src/vdp2.c
- yabause/src/vdp2.h
- yabause/src/vidshared.h
- yabause/src/vidsoft.c
- yabause/src/vidsoft.h
- yabauseut/src/vdp2.c
Cotton Boomerang, Radiant Silvergun, Scud and Dead or Alive all seem to work well with these changes. Some of the YabauseUT tests have had interlacing added and the results on Yabause match the hardware.
> Add support for double density interlace

- yabause/src/cs2.c
Cs2Area->datatranspartition->block[Cs2Area->datanumsecttrans] can be NULL when loading savestates in games such as Burning Rangers, especially during load times. This PR prevents a null pointer dereference that will crash the emulator and logs the error to the CD log. The game doesn't seem to be negatively affected by simply returning 0 and continues normally.
> Prevent null pointer dereference in cs2.c

- yabause/src/runner/CMakeLists.txt
This should fix the CircleCI linking issue.
> Add thread libraries to runner port

- yabause/src/vdp2.c
- yabauseut/src/sh2.c
- yabauseut/src/smpc.h
- yabauseut/src/vdp2.c
Hardware tests seem to indicate that the number of lines between vblank-out and vblank-in is actually 225 or 241. See the image below taken from hardware:
See linecount_test() to see how this was determined. Changing yabsys.VBlankLineCount to 225 makes the results of the test on Yabause match hardware.
Also add tests for the sh2 cache and vdp2 sprite window.
> Change the number of vblank lines to match hardware tests

- yabause/src/titan/titan.c
- yabause/src/vidsoft.c
Sprite window requires that sprites be processed before the rest of the layers. The results for the test in my other PR should now match hardware.
> Implement Vdp2 sprite window

- yabause/src/smpc.c
- yabauseut/src/smpc.c
The INTBACK system manager interrupt seems to always happen around lines 207-209 of a display, regardless of when the command is issued after VBLANK-in. When SMPC status and peripheral data are requested at the same time, the status is returned after about 4 lines, and then the peripheral data is returned the next frame around lines 207-209 if a continue request is issued. 
These changes fix the controls in Megaman X4 and Virtua Racing.
> Improve smpc intback timing

- yabause/src/memory.c
This change is only aesthetical, it's a suggestion based on code style guidelines from the Linux Kernel.
[Linux kernel coding style](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892)
> Avoiding conditional directives that break statements

- yabause/src/vidshared.h
- yabause/src/vidsoft.c
- yabauseut/src/scu.c
Dracula X sets the cycle pattern registers incorrectly for NBG3, resulting in the tiles on the data select screen being offset. 
Hardware tests suggest the following explanation:
Tile fetch has to occur during a certain timing window, otherwise the previously fetched data is used. This will affect the first tile in each scanline and that tile will use the data from the last tile of the previous scanline.  Since the tile pipeline didn't advance when it should have, all tiles after that first bad tile are offset.
The first and last tiles of the data select screen are transparent, so the junk tile effect is not visible in this case.
It's faster to just check for the Dracula X settings, but if other games use bad settings it will have to be changed to a full check.
Before
After
> Fix Dracula X data select screen

- yabause/src/titan/titan.c
- yabause/src/titan/titan.h
When all of the pixels in a screen are opaque and special priority isn't being used, layers can be sorted in advance to avoid having to do it per-pixel. This gives a performance boost for games that don't use those features. For example the bios CD player screen goes from 187 to 215 fps average on my system, which is about a 15% increase in performance.
> Vidsoft: add simplified priority optimization

- yabause/src/titan/titan.c
- yabause/src/vidsoft.c
These changes make it so that interlaced layers are written linearly to their framebuffers instead of skipping every other line. This allows the framebuffer size to be reduced by half, which improves cache usage and reduces time spent erasing pixels.
With these changes Dead or Alive goes from 63 to 88 fps average on my system.
> vidsoft: optimize interlaced modes

- yabause/src/vidsoft.c
Color offset was unimplemented for the back screen, resulting in incorrect screen transitions. Line color screen was also unimplemented for the sprite layer, causing the water to not be transparent over sprites.
> vidsoft: fix dracula x water and fade outs

- yabause/src/cocoa/YabauseGLView.m
This was only a problem for people with integrated gpu’s.
As OpenGL on OSX per default makes use of the legacy profiler, you have to specifically say you want to use the CORE profiler to be able to use anything OpenGL related above version 2.1.
The same problem occurs on the Qt version, but i haven't been able to fix it there yet...
> Fixed black screen on OSX Cocoa for integrated GPU

- yabause/src/runner/yui.cpp
This commit adds automated testing of games to the runner port. Screenshots are taken at specified frame numbers and compared with known good ones. The current set can be seen here: https://github.com/d356/yabauseut-bin/tree/master/game_screenshots
Two data files are required to run it. The first contains the game names, screenshot frame times and start button press times. The second contains the paths to the games on the user's hard drive.
Current data file:
http://pastebin.com/UpvPKHuU
Example paths file:
http://pastebin.com/pHNv98V9
This needs to be integrated with a web app that hooks into github like described here: https://developer.github.com/guides/building-a-ci-server/
> runner: add automated game testing

- yabause/src/scsp.c
- yabause/src/vdp1.c
IMPROVED_SAVESTATES needs to be defined since this will break savestate compatibility. Fixes  #173
> add vdp1 framebuffer and more scsp slot variables to savestates

- yabause/src/vidsoft.c
Dead or Alive requires the lower bits of colorbank to be ignored.
Before
After
> vidsoft: fix incorrect colors on characters in dead or alive

- appveyor.yml
- yabause/src/qt/CMakeLists.txt
- yabause/src/vidsoft.c
- yabause/src/ygles.c
The cpack script needs to be modified so it is currently disabled for this build. Also Direct X is disabled for this build due to a compile error involving dxerr. Dxerr is actually deprecated and doesn't work in Visual Studio 2015 either so it should probably be replaced with FormatMessage.
> add msys2 x86_64 build to appveyor

- yabause/src/vidsoft.c
- yabauseut/src/vdp2.c
DeltaKax is ignored if the coefficient table bank isn't specified for certain rotation settings.
> vidsoft: fix sonic r and all star baseball 97 backgrounds

- yabause/src/qt/ui/UISettings.cpp
- yabause/src/qt/ui/UISettings.ui
- yabause/src/qt/ui/UIYabause.cpp
- yabause/src/qt/ui/UIYabause.h
- yabause/src/vdp1.c
- yabause/src/vdp1.h
- yabause/src/vidogl.c
- yabause/src/vidsoft.c
This option automatically resizes the window to force pixels to have the native aspect ratio. Either 2x or 4x scaling is possible. This option is under Settings -> Video.
> qt/vidsoft: add integer video scaling option in windowed mode

- yabause/src/scsp.c
- yabause/src/scspdsp.c
This improves the volume levels of many sounds, adds cd audio, and saturates dsp math to reduce clipping in the bios intro sound.
> new scsp: implement mixing, cd audio, dsp saturation

- appveyor.yml
- yabause/src/CMakeLists.txt
- yabause/src/m68kcore.h
- yabause/src/m68kmusashi.c
- yabause/src/m68kmusashi.h
- yabause/src/musashi/m68k.h
- yabause/src/musashi/m68k_in.c
- yabause/src/musashi/m68kconf.h
- yabause/src/musashi/m68kcpu.c
- yabause/src/musashi/m68kcpu.h
- yabause/src/musashi/m68kdasm.c
- yabause/src/musashi/m68kmake.c
- yabause/src/musashi/readme.txt
- yabause/src/qt/QtYabause.cpp
- yabause/src/qt/QtYabause.h
- yabause/src/qt/YabauseThread.cpp
- yabause/src/qt/ui/UISettings.cpp
- yabause/src/qt/ui/UISettings.ui
- yabause/src/qt/ui/UIYabause.cpp
This adds Musashi as one of the 68k core options. Musashi was relicensed to MIT in 2013 and is compatible with with GPL now. Musashi has a few advantages:
Well tested
Compiles quickly
About 10% fps increase on my system
There is no 68k core selection option in the Qt port so it has to be set manually at the moment.
> 68k: add musashi as a 68k core option

- yabause/src/qt/ui/UIMemoryEditor.cpp
Fixed issued with Memory Editor close button being disabled. Issue #206
> Fixed issue #206

- yabause/src/aosdk/ao.h
- yabause/src/aosdk/eng_ssf.c
- yabause/src/aosdk/ssf.c
- yabause/src/qt/YabauseThread.cpp
- yabause/src/qt/ui/UISettings.cpp
- yabause/src/qt/ui/UISettings.ui
- yabause/src/qt/ui/UIYabause.cpp
- yabause/src/scsp.c
- yabause/src/scsp.h
- yabause/src/yabause.c
- yabause/src/yabause.h
The new scsp has been added as a run-time option to the Qt port under Settings -> Sound. 
The minissf loader was previously unable to find library files because the path was not present in the filename.
Also an out of bounds read of the efreg registers was fixed.
> scsp/qt: add new scsp option to settings, fix minissf loading

- yabause/src/scsp.c
- yabause/src/scsp.h
- yabause/src/yabause.c
This commit improves the synchronization of the new scsp and 68k to a sample level. Some things I've noticed to have improved are:
Radiant Silvergun press start sound
Bios advanced controls button sound
Scorcher track 3 has no missing notes
> new scsp: run sound subsystem at sample-level timing

- yabause/src/gameinfo.c
- yabause/src/sh2_dynarec/assem_arm.c
- yabause/src/sh2_dynarec/assem_x64.c
- yabause/src/sh2_dynarec/assem_x86.c
- yabause/src/sh2_dynarec/sh2_dynarec.c
- yabause/src/sh2d.c
- yabause/src/vidogl.c
- yabause/src/ygles.c
- yabause/src/yglshaderes.c
This commit fixes all warnings on Travis CI for GCC and clang on Linux except for some clang warnings caused by Qt include files.
> build: fix warnings on gcc/clang linux

- .travis.yml
- yabause/src/CMakeLists.txt
This commit enables warnings as errors for Linux clang and GCC builds on Travis CI.
> ci: enable -Werror for linux builds

- yabause/src/musashi/CMakeLists.txt
- yabause/src/vdp1.c
- yabause/src/vdp1.h
- yabause/src/vdp2.c
- yabause/src/vidogl.c
- yabause/src/vidsoft.c
Winter Heat blanks the screen using the Vdp2 disp register, which requires erasing the layers drawn previously.
> vidsoft: improve winter heat screen transitions

- yabause/src/sh2cache.c
- yabause/src/sh2int.c
YAB_WANT_SH2_CACHE has to be enabled.
> sh2 cache: fix astal when using a real bios

- yabause/src/cs2.c
Hi there,
This is a patch from uoYabause.
https://github.com/devmiyax/yabause/issues/154
(cherry picked from commit 7b49752d54f911656e3f27b30421a7664a435928)
> fix #154 no background sound on SEGA RALLY CHAMPIONSHIP

- yabause/src/CMakeLists.txt
This fix https://github.com/Yabause/yabause/issues/321
> Older gcc (4.8) doesn't supports enough CXX11 for Codegen

- .travis.yml
- yabause/src/android/CMakeLists.txt
- yabause/src/android/android.cmake
- yabause/src/android/jni/Application.mk
With this change, the Android port can be compiled by only
setting ANDROID_HOME and ANDROID_NDK_HOME.
It's based on d356 script for travis.
> Improve Android build

- yabause/src/qt/YabauseThread.cpp
- yabause/src/qt/ui/UIDebugSCUDSP.cpp
- yabause/src/qt/ui/UIHexEditor.cpp
- yabause/src/qt/ui/UIYabause.cpp
It is now possible to use non-ascii characters in paths/filenames.
> Using QFile::encodeName to convert paths

- yabause/src/vidsoft.c
It seems all color calculation modes can be used when
sprites are RGB, and not only the MSB one.
It could explains a number of transparency problems.
This fix the transparency problem on Asuka 120% menu.
> Enable all color calculation modes for RGB

- yabause/src/vidsoft.c
It seems Beach de Reach use (prohibited) color mode 6 and expect it
to behave like mode 5 (16bpp).
Fixes: https://github.com/Yabause/yabause/issues/253
> Added prohibited color mode 6

- yabause/src/qt/yabause.desktop.in
In openSUSE obs package don't build because wrong Category in .desktop file.
P.S. (Qt port) removed for aesthetics.
> fix wrong Category and building in openSUSE OBS

- yabause/src/ygl.h
- yabause/src/ygles.c
I noticed that Yabause was crashing when attempting to create an OpenGL window on my Mac. It looks like `glGetString(GL_EXTENSIONS)` is returning a null pointer - I'm not sure why, but there's probably another bug at play. This doesn't fix that bug, but it at least means that Yabause pops up a "Cannot initialize Video" window instead of crashing.
I've also added a commit which suppresses the build warning about building multiple OpenGL headers on OS X.
> OpenGL: Fix potential segmentation fault from calling strstr on a null pointer

- yabause/src/qt/ui/UIDebugVDP1.cpp
- yabause/src/vdp1.c
- yabause/src/vdp1.h
Not a fix, but a simple change to enumerate all command tables in VDP1 debug.
It's also nice to know how many command tables are being processed :)
> Enumerate each command table in QT VDP1 debug window
